// 365 frases motivacionais para cada dia do ano

export const DAILY_QUOTES: string[] = [
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "A excelência não é um destino, mas uma jornada contínua.",
  "Cada cliente atendido com cuidado é uma semente plantada para o futuro.",
  "Consistência é o segredo dos grandes resultados.",
  "O trabalho bem feito fala mais alto que qualquer promessa.",
  "Quem serve bem, conquista para sempre.",
  "Transformar sonhos em realidade exige disciplina, foco e ação.",
  "Um passo de cada vez, mas sempre em frente.",
  "A confiança se constrói entrega a entrega.",
  "Grandes conquistas começam com uma decisão firme.",
  "O detalhe que você cuida hoje é o diferencial que te define amanhã.",
  "Seu esforço de hoje é o seu orgulho de amanhã.",
  "Atender bem é um ato de respeito e cuidado.",
  "A qualidade do seu trabalho define a grandeza do seu legado.",
  "Cada processo concluído é uma história de superação.",
  "Seja a razão do sorriso de alguém hoje.",
  "Profissionalismo é fazer o correto mesmo quando ninguém está vendo.",
  "O tempo investido em aprender nunca é perdido.",
  "Resultados extraordinários surgem de esforços consistentes.",
  "Cada dia é uma nova oportunidade de superar o ontem.",
  "A dedicação é o atalho mais longo — e o mais seguro.",
  "Inovar é enxergar possibilidades onde outros veem obstáculos.",
  "Cuidar das pessoas é o maior negócio que existe.",
  "O sucesso coletivo começa com o comprometimento individual.",
  "Sua atitude define muito mais que suas habilidades.",
  "Fazer a diferença é uma escolha que se renova todo dia.",
  "O cliente satisfeito é a melhor propaganda que existe.",
  "Persistência transforma tentativas em conquistas.",
  "Um time unido supera qualquer desafio.",
  "Propósito claro gera energia inesgotável.",
  "Não existe vento favorável para quem não sabe onde quer chegar.",
  "O caminho para o topo é feito de pequenas vitórias diárias.",
  "Servir com excelência é a maior forma de liderança.",
  "Planejamento é o mapa que transforma visão em realidade.",
  "A humildade é a base de toda grande conquista.",
  "Cada desafio superado revela uma força que você não sabia que tinha.",
  "O respeito ao cliente é o fundamento de qualquer relação duradoura.",
  "Foco no que importa, energia no que transforma.",
  "A pontualidade é uma forma de dizer: eu te valorizo.",
  "Excelência não é perfeição — é entregar o seu melhor, sempre.",
  "A gratidão abre portas que o talento sozinho não consegue.",
  "Quando o propósito é claro, o esforço se torna leveza.",
  "Cada cliente é uma história única que merece atenção total.",
  "A disciplina de hoje é a liberdade de amanhã.",
  "Fazer mais do que o esperado é o segredo do crescimento.",
  "O verdadeiro profissional resolve, não reclama.",
  "Cuidar bem é a arte de quem ama o que faz.",
  "Grandes jornadas começam com um único passo corajoso.",
  "Seu nome é sua marca — cuide dele com zelo.",
  "O presente momento é onde toda mudança começa.",
  "Transparência gera confiança, confiança gera negócios.",
  "Aprender com os erros é crescer; repetir os erros é estagnar.",
  "O trabalho em equipe multiplica resultados e divide desafios.",
  "Cada 'sim' que você diz ao cliente deve ser seguido de ação.",
  "Entusiasmo é contagioso — comece por você.",
  "A organização é o primeiro passo para a produtividade.",
  "Quem tem clareza sobre seus objetivos não se perde nos obstáculos.",
  "A experiência do cliente começa na primeira impressão.",
  "Superar expectativas é transformar clientes em fãs.",
  "Grandes resultados exigem grandes responsabilidades.",
  "O profissionalismo se manifesta nos detalhes que ninguém pediu.",
  "Crescimento real vem de sair da zona de conforto.",
  "Cada tarefa concluída é um tijolo no edifício do seu sucesso.",
  "Seja o tipo de pessoa que você gostaria de encontrar.",
  "A paciência é uma virtude que multiplica frutos.",
  "Quem não crepe aprende; quem aprende cresce; quem cresce inspira.",
  "O comprometimento diário supera o talento ocasional.",
  "Uma palavra gentil pode mudar o dia de alguém.",
  "Soluções criativas nascem de mentes abertas e corajosas.",
  "Hoje é uma boa oportunidade de fazer algo extraordinário.",
  "O seu melhor é sempre suficiente quando dado com intenção.",
  "Clareza de propósito é o maior combustível da produtividade.",
  "Cada obstáculo superado é uma prova de que você é capaz.",
  "A confiança do cliente é um tesouro que se constrói todos os dias.",
  "A alegria no trabalho é sinal de quem encontrou seu caminho.",
  "Fazer o bem sempre volta de formas inesperadas.",
  "O sucesso sustentável é construído sobre valores sólidos.",
  "Seja consistente mesmo quando os resultados ainda não aparecem.",
  "Quem cuida das pessoas, cuida do negócio.",
  "A clareza na comunicação é a base de qualquer parceria de sucesso.",
  "Feito é melhor que perfeito — mas excelente é melhor que ambos.",
  "Atender prontamente é respeitar o tempo do outro.",
  "O crescimento começa onde a zona de conforto termina.",
  "Cada aprendizado é um investimento que nunca se deprecia.",
  "A generosidade no trabalho cria ambientes de alto desempenho.",
  "Resolver problemas com calma é sinal de maturidade profissional.",
  "Quem ajuda, prospera. Quem prospera, pode ajudar mais.",
  "O sucesso de longo prazo é construído na integridade diária.",
  "Seja a solução que o cliente não sabia que precisava.",
  "O melhor investimento é no relacionamento com as pessoas.",
  "Propósito + Esforço + Consistência = Resultado inevitável.",
  "Um serviço de qualidade fala mais alto que qualquer marketing.",
  "A dedicação silenciosa produz resultados eloquentes.",
  "Celebre cada conquista — ela foi conquistada com esforço.",
  "O processo importa tanto quanto o resultado.",
  "Onde há comprometimento, há crescimento.",
  "Cada dia trabalhado com propósito aproxima você do seu objetivo.",
  "Inovação é a capacidade de enxergar o velho com olhos novos.",
  "Sua presença importa — esteja presente de verdade.",
  "A empatia é a mais poderosa ferramenta de negócios.",
  "Fazer o básico bem feito já te coloca à frente de muitos.",
];

export function getDailyQuote(month: number, day: number): string {
  const date = new Date(2026, month - 1, day);
  const startOfYear = new Date(2026, 0, 1);
  const dayOfYear = Math.floor(
    (date.getTime() - startOfYear.getTime()) / (1000 * 60 * 60 * 24)
  );
  return DAILY_QUOTES[dayOfYear % DAILY_QUOTES.length];
}

export function getTodayQuote(): string {
  const today = new Date();
  return getDailyQuote(today.getMonth() + 1, today.getDate());
}
